### ISSUE TITLE
http example code counter

### ISSUE THREAD

**Issue by RobViren** [exosite-ready/er_sdk#1]
I could be wrong, but it appears that the counter used as example data, in exosite_send_http.c, is never assigned a value. I really like the function breakdown. I've been working on some cpp code just calling curl commands, but this would have been much easier.

**Comment by szilveszterb** [comment]
Variables with static storage duration are initalized to 0. It might have enhanced readability if we provided explicit initalization though. And in this case counter could be a local variable as well.

Thanks for looking into this!
